### ISSUE TITLE
Registering a component with pooling disabled causes errors

### ISSUE THREAD

**Issue by vegeta897** [ecsyjs/ecsy-devtools#66]
Using `ecsy@0.4.0`, when registering a component with the pooling argument of `false`, the ECSY devtools will not function and show this error in the console on every `world.execute()`

    VM11588:128 Uncaught TypeError: Cannot read property 'T' of undefined
      at Object.window.__ECSY_DEVTOOLS.refreshStats (<anonymous>:128:22)
      at World.<anonymous> (<anonymous>:66:27)
      at Engine.update (Engine.ts:13)
      at Engine.ts:18

**Comment by vegeta897** [comment]
Here is a simple glitch.me repro: https://ecsy-devtools-pooling.glitch.me/
Source: https://glitch.com/edit/#!/ecsy-devtools-pooling

In testing this I believe I have found the cause of the error.

In `ecsy-devtools/index.js` lines [116](https://github.com/MozillaReality/ecsy-devtools/blob/b87de1820d97dd1d6ed0a0144ece3900bf4265f2/src/content/index.js#L116) to 124:

    for (name in world.componentsManager._componentPool) {
        if (!_pools[name]) {
            _pools[name] = {
                lastPoolSize: 0
            };
        }

        let pool = world.componentsManager._componentPool[name];
        var cName = pool.T.name;

This iterates over the `_componentPool` object, which uses component ID indexes mapped to ObjectPool values. When a component is registered with `false` as the pool, the value is undefined (this looks to be on purpose, judging by [the code in ECSY](https://github.com/MozillaReality/ecsy/blob/dev/src/ComponentManager.js#L51)). This function sets `pool` to undefined, and so `T` cannot be read.

**Comment by vegeta897** [comment]
Updated ECSY devtools to version 0.1.3 released on Firefox today.

The console error spam still happens, and it also makes the devtools fail to connect to the app:

1. Visit https://ecsy-devtools-pooling.glitch.me/
2. The ECSY extension button will show that ECSY is detected on this page
3. Hit F12 to see the pooling error on every execute (1 per second in this example)
4. Open the devtools to see that they refuse to connect to the ECSY app

On a page that is identical to the above, but doesn't disable component pooling:

1. Visit https://ecsy-devtools-nonpooling.glitch.me/
2. The ECSY extension button will show that ECSY is detected on this page
3. Hit F12 to see no pooling errors
4. Open the devtools to see that they connect properly

**Comment by fernandojsg** [comment]
@vegeta897 I just fixed the pool issue, I pushed v0.1.4 to the addons store in firefox and I tried your examples and it works. Can you please verify it too?

**Comment by vegeta897** [comment]
@fernandojsg thank you SO much, it works perfectly!
