### ISSUE TITLE
Please link to the Chrome and Firefox extensions in the readme

### ISSUE THREAD

**Issue by triptych** [ecsyjs/ecsy-devtools#69]
The Chrome and Firefox extensions are mentioned in the blog, but nowhere in the readme. Please add them.

https://blog.mozvr.com/ecsy-developer-tools/
https://chrome.google.com/webstore/detail/ecsy-devtools/cdmidpfffmlibnnbhkfbobpghgfmhdhk

https://addons.mozilla.org/en-US/firefox/addon/ecsy-devtools/

**Comment by fernandojsg** [comment]
Thanks for the suggestion. Fixed!
